# This file was generated by GoReleaser. DO NOT EDIT.
cask "ska" do
  name "ska"
  desc "SKA is a CLI and Library to scaffold, maintain and update from upstream blueprint your projects."
  homepage "https://github.com/gchiesa/ska"
  version "1.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ska"

  on_macos do
    on_intel do
      url "https://github.com/gchiesa/ska/releases/download/v#{version}/ska_#{version}_darwin_amd64.tar.gz"
      sha256 "5dd6edf47eb2df21780e8d1015af331f729d091057a02782b3152112398c03df"
    end
    on_arm do
      url "https://github.com/gchiesa/ska/releases/download/v#{version}/ska_#{version}_darwin_arm64.tar.gz"
      sha256 "c21c9b41b9eb2cc676a5023fa9c9c220447ad8929d1eea996b4322e69845c6f5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gchiesa/ska/releases/download/v#{version}/ska_#{version}_linux_amd64.tar.gz"
      sha256 "1066448f1826d3901273096a1792be3c08a4572a6b55ba4c2e8b67032ca937e4"
    end
    on_arm do
      url "https://github.com/gchiesa/ska/releases/download/v#{version}/ska_#{version}_linux_arm64.tar.gz"
      sha256 "bd1b403150e7ac99b6c998416289ce6eb64b2c713bf94852ea928c93b5c80b54"
    end
  end

  # No zap stanza required
end
