# This file was generated by GoReleaser. DO NOT EDIT.
cask "ska" do
  name "ska"
  desc "SKA is a CLI and Library to scaffold, maintain and update from upstream blueprint your projects."
  homepage "https://github.com/gchiesa/ska"
  version "1.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ska"

  on_macos do
    on_intel do
      url "https://github.com/gchiesa/ska/releases/download/v#{version}/ska_#{version}_darwin_amd64.tar.gz"
      sha256 "1cbd00feaf9cb5e33d48b599a6ee7b1a3620bf37055fbb7395b80293411a237b"
    end
    on_arm do
      url "https://github.com/gchiesa/ska/releases/download/v#{version}/ska_#{version}_darwin_arm64.tar.gz"
      sha256 "a8fcd822f1e26dce871577902f82dee7b56f5817961f855359d00c693a0d2fb1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gchiesa/ska/releases/download/v#{version}/ska_#{version}_linux_amd64.tar.gz"
      sha256 "441b15c3ce3fd88dc1677e7fe132dd042403da7a84a74bcbd15b0dee39837ce0"
    end
    on_arm do
      url "https://github.com/gchiesa/ska/releases/download/v#{version}/ska_#{version}_linux_arm64.tar.gz"
      sha256 "a9a43ffe673c7bf08f44a0d461e55b8a882a09d437e96386e31e2cc284f28d9f"
    end
  end

  # No zap stanza required
end
