# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ska < Formula
  desc "SKA is a CLI and Library to scaffold, maintain and update from upstream blueprint your projects."
  homepage "https://github.com/gchiesa/ska"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gchiesa/ska/releases/download/v1.2.2/ska_1.2.2_darwin_amd64.tar.gz"
      sha256 "90e4a675fbde26fa140d90c29c08d100ed42cd4f8ad4b1a984a948b49f4c7a6d"

      def install
        bin.install "ska"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gchiesa/ska/releases/download/v1.2.2/ska_1.2.2_darwin_arm64.tar.gz"
      sha256 "285af6bcfb9b3de00f345cd76189a105b3aa5094a1109a1008d6674e668ccfc7"

      def install
        bin.install "ska"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gchiesa/ska/releases/download/v1.2.2/ska_1.2.2_linux_amd64.tar.gz"
      sha256 "93eb0fb8af7c93b0e28bf83e8fd4a096f15dbcd43dfa0319dc897a6027e29244"
      def install
        bin.install "ska"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gchiesa/ska/releases/download/v1.2.2/ska_1.2.2_linux_armv6.tar.gz"
      sha256 "72bd7c4c9a1e49d6ae190bb044db6521fe200470ebe2bd28fb4d0b2b539206cb"
      def install
        bin.install "ska"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gchiesa/ska/releases/download/v1.2.2/ska_1.2.2_linux_arm64.tar.gz"
      sha256 "abe5c461a0ac3d28a05e4200266ab191c254576a408b9c4d23992c84f8c55574"
      def install
        bin.install "ska"
      end
    end
  end
end
