# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ska < Formula
  desc "SKA is a CLI and Library to scaffold, maintain and update from upstream blueprint your projects."
  homepage "https://github.com/gchiesa/ska"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gchiesa/ska/releases/download/v1.2.1/ska_1.2.1_darwin_amd64.tar.gz"
      sha256 "90d48f3f01ebe33f74cd96513bff52ba0499ad039eeb470ff8d4c1aafeabebe3"

      def install
        bin.install "ska"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gchiesa/ska/releases/download/v1.2.1/ska_1.2.1_darwin_arm64.tar.gz"
      sha256 "b307da31d4eea991c7d5aba5bbf209aef7dce157cef8ca0ea44f80f22e70f9c0"

      def install
        bin.install "ska"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gchiesa/ska/releases/download/v1.2.1/ska_1.2.1_linux_amd64.tar.gz"
      sha256 "194dcec9294d82b86ffa9c397324beec62d0e240999dbffca593724bab4cf592"
      def install
        bin.install "ska"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gchiesa/ska/releases/download/v1.2.1/ska_1.2.1_linux_armv6.tar.gz"
      sha256 "a0349546892dc538a3ef740d1f59fc8d4664966eca6baa9970949bc4d9940aba"
      def install
        bin.install "ska"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gchiesa/ska/releases/download/v1.2.1/ska_1.2.1_linux_arm64.tar.gz"
      sha256 "140eae30f474171ad1afa642ac256a7461bf7c20afdddf2b61c3cdb8c35ac7b0"
      def install
        bin.install "ska"
      end
    end
  end
end
