# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ska < Formula
  desc "SKA is a CLI and Library to scaffold, maintain and update from upstream blueprint your projects."
  homepage "https://github.com/gchiesa/ska"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gchiesa/ska/releases/download/v1.2.0/ska_1.2.0_darwin_amd64.tar.gz"
      sha256 "4b8e1f68a810ac53382066848fe4405878dde2ff0f4ec32fff2c4bd43bd1aaf6"

      def install
        bin.install "ska"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gchiesa/ska/releases/download/v1.2.0/ska_1.2.0_darwin_arm64.tar.gz"
      sha256 "fe7a45643bcff4ed72829d184077e41107974fbd23ba6d603cadd4a5010c56a0"

      def install
        bin.install "ska"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gchiesa/ska/releases/download/v1.2.0/ska_1.2.0_linux_amd64.tar.gz"
      sha256 "190e1f6b88eb0b498e194e12fa67afda3d862ae507c124634b572f5fa416a08d"
      def install
        bin.install "ska"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gchiesa/ska/releases/download/v1.2.0/ska_1.2.0_linux_armv6.tar.gz"
      sha256 "9a38e954572cc825971976375dcddb3ff5b3ce1a3b47c11c14f452faa3d0ec81"
      def install
        bin.install "ska"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gchiesa/ska/releases/download/v1.2.0/ska_1.2.0_linux_arm64.tar.gz"
      sha256 "2f8cc7599d0af8ee71934f6559cbb748a2d1e15ceb243b573d3eeafeb6fc93f1"
      def install
        bin.install "ska"
      end
    end
  end
end
